#ifndef OP_CODE_H_
#define OP_CODE_H_

typedef enum
{
	INSTRUCTIONS,
	EXIT,
	UNDEFINED,
	PROCESS_INIT_REQUEST,
	PROCESS_INIT_RESPONSE,
	PROCESS_SUSPEND_REQUEST,
	PROCESS_SUSPEND_RESPONSE,
	PROCESS_KILL_REQUEST,
	PROCESS_KILL_RESPONSE,
	GET_SECOND_LEVEL_TABLE_REQUEST,
	GET_FRAME_REQUEST,
	READ_MEMORY_REQUEST,
	WRITE_MEMORY_REQUEST,
	DEBUGGING
}op_code;

#endif

